name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 7672939c-9b9f-4ae7-94ed-60a073bac0df
          heroku_app_name: strosinminerva
          heroku_email: strosinminerva@outlook.com
          usedocker: true
          docker_heroku_process_type: worker
          stack: "heroku-20"
          region: "eu"
        env:
          HD_DB_URI: "postgres://lqdgyegrjfscxi:a513e56bce93d2a52466d49c625bc59990125d38fec6b1d7f855edcfa8639e7a@ec2-52-19-96-181.eu-west-1.compute.amazonaws.com:5432/d52s77ijo3ff43"
          HD_API_HASH: "b1fc05cb6e99b67c6fca96538c6d7e7e"
          HD_API_ID: 1957706
          HD_BOT_TOKEN: "2112326002:AAHUS1WgBjjUDE9cpcQdnfDz-IGpq93xTtI"
          HD_COMPLETED_STR: "▰"
          HD_REMAINING_STR: "▱"
          HD_MAX_QUEUE_SIZE: 5
          HD_SLEEP_SECS: 10
          HD_IS_PRIVATE: true
          HD_AUTH_USERS: -1001670573538
          HD_OWNER_ID: 831054990
          HD_TRACE_CHANNEL: -1001545909956
